org.gradle.jvmargs=-Xmx2600m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
systemProp.https.protocols=TLSv1.2
systemProp.jdk.tls.client.protocols=TLSv1.2
